"""events_and_notifications

Revision ID: 304bbdeff4fb
Revises: 0a359baf86a5
Create Date: 2026-03-05 18:24:54.423915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304bbdeff4fb'
down_revision: Union[str, Sequence[str], None] = '0a359baf86a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('order_id', sa.String(length=64), nullable=False))
    op.add_column('events', sa.Column('user_id', sa.String(length=64), nullable=False))
    op.add_column('events', sa.Column('event_type', sa.String(length=32), nullable=False))
    op.add_column('events', sa.Column('event_occurred_at', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('published_to_kafka', sa.Boolean(), nullable=False))
    op.drop_column('events', 'type')
    op.drop_column('events', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('events', 'published_to_kafka')
    op.drop_column('events', 'event_occurred_at')
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'user_id')
    op.drop_column('events', 'order_id')
    op.drop_table('notifications')
    # ### end Alembic commands ###
